### ISSUE TITLE
[Bug] Descarga Masiva Facturas emitidas

### ISSUE THREAD

**Issue by pixelead0** [LinuxCabal/admin-cfdi#1]
Al intentar descargar las facuras emitidas, no logro hacerlo.
Se loguea satisfactoriamente al SAT, pero al parecer al 'seleccionar' la fecha se pierde, porque el formulario es diferente al de 'facturas recibidas'. 

Esto provoca que no encuentre facturas emitidas en el mes seleccionado.

**Comment by ghost** [comment]
En efecto, los nombres de los controles (que **no son estandar** por cierto, cortesía de los desarrolladores del SAT) algo ha cambiado en la página del SAT por que hasta la semana pasada funcionaba sin problemas...

Lo reviso pero esto pasará siempre que el SAT haga algún cambio en la página... así que agradeceremos su notificación inmediata...

**Comment by ghost** [comment]
El control input donde se recibe la fecha, por default esta deshabilitado, hay que habilitarlo para poder enviar la fecha buscada, esto se hace con:

```
browser.execute_script('arguments[0].removeAttribute("disabled");', txt)
```

Es la línea que esta fallando...

**Comment by ghost** [comment]
Resuelto en 0.2.3
