### ISSUE TITLE
Para que funcione en python 3.2

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#10]
Buen día, los requerimientos son python 3.4, pero en "ubuntu" tengo python 3.2.
Para hacer que funcione es necesario modificar el archivo "pyutil.py":

En la lineas 

> 1371:`data += u’\n\nAlumno: %s\nCURP: %s’ % (`
> 1373:`data += u’\nAcuerdo de incorporación ante la SEP %s %s’ % (`

eliminar la "u", quedando así: 

> 1371: `data += ‘\n\nAlumno: %s\nCURP: %s’ % (`
> 1373: `data += ‘\nAcuerdo de incorporación ante la SEP %s %s’ % (`

En el mismo archivo, python 3.2 falla en la línea #28, la comenté y cambie por:

> `#from subprocess import DEVNULL`
> `from subprocess import Popen, PIPE, STDOUT`
> `try:`
> `from subprocess import DEVNULL # py3k`
> `except ImportError:`
> `import os`
> `DEVNULL = open(os.devnull, 'wb')`

Saludos!

**Comment by ghost** [comment]
Los he incorporado en esta rama: https://github.com/LinuxCabal/admin-cfdi/tree/uuid_in_name
