### ISSUE TITLE
Validar nombres de campos en reporte

### ISSUE THREAD

**Issue by mimex** [LinuxCabal/admin-cfdi#11]
Durante la reunión del miércoles ingresamos por error el nombre del campo UUID en minúsculas en el apartado de reportes, generando con esto que la interfaz gráfica quedara ciclada;

```
{uuid}|{fecha}|{serie}{folio}|{emisor_nombre}|{emisor_rfc}|{receptor_nombre}|{receptor_rfc}|{subTotal}|{traslado_iva_16}|{total}
```

La salida de la terminal es la siguiente;

```
ERROR:pygubu.builderobject:Failed to set property 'from_' on class '<class 'tkinter.Spinbox'>'. TclError: -to value must be greater than -from value
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1490, in __call__
    return self.func(*args)
  File "admincfdi.py", line 1525, in button_generate_report_click
    line_csv = self._make_report(f, data)
  File "admincfdi.py", line 1537, in _make_report
    return self.util.get_info_report(path, data, self.g)
  File "/home/fipasoft/dev/admin-cfdi/pyutil.py", line 618, in get_info_report
    info = options['fields_report'].format(**data).split('|')
KeyError: 'uuid'
```

Considero que además de validar los nombres de los campos podríamos agregar a la interfaz un select multiple para establecer orden y aparición de los campos.

**Comment by ghost** [comment]
Eso ultimo me gusta +1

**Comment by ppaez** [comment]
En el renglón 618 una opcion podría ser usar una instancia de Template del módulo string, parecido a esto:

```
from string import Template
tmpl = Template(' ${uuid} ')
texto = tmpl.safe_substitute(**data)
```

Si data no tiene la llave 'uuid', el resultado queda '  ${uuid} '  y no se genera una excepción.  En el reporte aparecerá el nombre del campo, indicando al usuario que lo tiene que corregir.

**Comment by mimex** [comment]
Muchas gracias Patricio, intentaré con esa solución.

**Comment by mimex** [comment]
@ppaez tal como lo sugeriste probé safe_substitute y funcionó, solo tuve que agregar un replace de '{' por '${' para mantener compatibilidad con la definición actual de los reportes {campo1},{campo2}, etc

```
+        tmpl = Template(options['fields_report'].replace('{', '${'))
+        info = tmpl.safe_substitute(**data).split('|')
```

Si les parece bien puedo solicitar la mezcla como hotfix/0.2.5

**Comment by ppaez** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Resuelto en 0.2.6
