### ISSUE TITLE
Error en el blog

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#12]
En: http://blog.facturalibre.net/stories/admin-cfdi2.html

> Si usas Windows no es necesario usar sudo:
> `pip install seleniumn pygubu`
> sobra la "n" en "seleniumn"

**Comment by ghost** [comment]
Gracias, este fin de semana lo arreglo...

Saludos

**Comment by ghost** [comment]
Arreglado, gracias...
