### ISSUE TITLE
Selección de un día, se desconecta sin descargar cuando hay comprobantes.

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#13]
Al seleccionar un día con comprobantes,  la aplicación abre Firefox e inicia sesión, localiza el día, muestra los comprobantes, al iniciar la descarga (a veces no se observa) de manera automatica vuelve a buscar el día y hace click en buscar, lo que ocasiona que se cierre la sesión y aparece ciclado el mensaje "Desconectando"

Coloque unos mensajes 'msg_user' despues de cada "click" para ver en que momento despues de comenzar a descargar hacia la segunda busqueda del día y veo que en la línea #501 hay un aviso de Bug del SAT, para desactivarlo lo comenté hasta antes del try.

admincfdi.py:

``` python
            # Bug del SAT - MrE - se esta desconectado al correr este código.
            '''
            if data['type_invoice'] != 1 and data['search_day'] != '00':
                combo = browser.find_element_by_id(self.g.SAT['day'])
                sb = combo.get_attribute('sb')
                combo = browser.find_element_by_id(
                    'sbToggle_{}'.format(sb))
                combo.click()
                self._set('msg_user', 'DEBUG 9...', True)
                self.util.sleep(2)
                if data['search_month'] == data['search_day']:
                    links = browser.find_elements_by_link_text(
                        data['search_day'])
                    for l in links:
                        p = l.find_element_by_xpath(
                            '..').find_element_by_xpath('..')
                        sb2 = p.get_attribute('id')
                        if sb in sb2:
                            link = l
                            break
                else:
                    link = browser.find_element_by_link_text(
                        data['search_day'])
                link.click()
                self._set('msg_user', 'DEBUG 10...', True)
                self.util.sleep(2)
                browser.find_element_by_id(self.g.SAT['submit']).click()
                self.util.sleep(sec)
            elif data['type_invoice'] == 2 and data['sat_month']:
                return self._download_sat_month(data, browser)
            '''
            try:
```

Con esto logré descargar todas las del día, pero no estoy seguro que sea correcto desactivar ese bloque de código, quizás algo dentro del Bug debe de correrse para que funcione correctamente al terminar.

Quizás el SAT quito su "BUG" y esto ahora genera el problema.

**Comment by ghost** [comment]
Tiene dos problemas la página del SAT, el primero es que no selecciona el mes o día a la primera, hay que hacerlo dos veces, y la segunda, es que cuando corresponde el número de mes con el número de día, también hay que hacerlo dos veces... solo hay que verificarlo

**Comment by mr-E** [comment]
Lo curioso es que desactive ese bloque de codigo y sin necesidad de hacerlo dos veces funciona la descarga. Pero no he intendado descargar un mes completo.

En este mismo rubro:
Tambien tuve que añadir mas tiempo en algunos sleeps, porque al estar lenta la carga de la pagina los enlaces no estan completamente descargados y se desconecta automaticamente (me di cuenta porque se ve la lista de comprobantes, pero los iconos de los comprobantes aun no se cargan en firefox, entonces sale un mensaje de "red lenta" y se desconecta).

Con esos dos sleeps modificados, antes de comenzar a leer los enlaces de XML y despues de terminar la ultima descarga conseguí mas estabilidad antes y despues de descargar. Pero quizas es a causa de que recibimos +100 diariamente a veces entre 200 y 300 comprobantes en algunos días.

Estoy aprendiendo a usar GitHub, ya vi como clonar la rama, la modificaré y propondre mis cambios. Quizas sería cosa de poner algunas opciones extra en la interfaz para que no se ejecute el codigo comentado si esto provoca desconexiones imprevistas (mi caso) y mas tiempo en los sleeps que sospecho impiden la descarga si la pagina no hay llegado completa para su descarga.

**Comment by mimex** [comment]
Muy bien!

Aunque aún no está definida por completo la forma de colaborar en el
proyecto hemos estado platicando sobre este modelo en las pasadas
reuniones: http://nvie.com/posts/a-successful-git-branching-model/ para
que lo tengas en cuenta al hacer tu pull-request

**Comment by ghost** [comment]
He visto otro software que te permite abrir una instancia del navegador con la página del SAT, pero esto obliga al usuario siempre a identificarse y esperar a hacer el filtro manualmente... pero se ve más bonito que lo haga todo solito, jejejje... pero si, se tiene el problema de que depende completamente de los cambios que haga el SAT de la página y del estado de su bendita red...

Si, es importante usar GitHub para los cambios...

Los tiempos los estableci en una maquina con una conexión de medio mega, realmente lenta pero estable... tal vez es un valor que deberíamos poner en la interfaz para el usuario, o tal vez ir registrando las salidas fallidas e ir aumentando el tiempo automáticamente...

Saludos

**Comment by mr-E** [comment]
Hoy me dejo de funcionar sin el código que maneja el "bug del sat"... para que me funcione tuve que añadir pausas antes de los clics.

Las pausas en el código dentro del "bug del sat" las puse al aventón quizás solo se necesitan en lugares estrategicos (pondre de momento lo que hice, en cuanto tenga oportunidad lo pongo GitHub, pero no tan "feo" a como lo estoy usando):

``` python
            # Bug del SAT
            # MrE - se esta desconectado al correr este código. Necesita Pausa entre clicks
            #''' #el día de hoy 2015.02.03 no funciona sin este codigo
            if data['type_invoice'] != 1 and data['search_day'] != '00':
                self._set('msg_user', 'Pausa 5 segundos. DEBUG 9...', True)
                self.util.sleep(5) # pausa forzada o se desconecta
                combo = browser.find_element_by_id(self.g.SAT['day'])
                sb = combo.get_attribute('sb')
                combo = browser.find_element_by_id(
                    'sbToggle_{}'.format(sb))
                combo.click()
                self._set('msg_user', 'Pausa 3 segundos. DEBUG 10...', True)
                self.util.sleep(3) # pausa forzada o se desconecta
                if data['search_month'] == data['search_day']:
                    links = browser.find_elements_by_link_text(
                        data['search_day'])
                    for l in links:
                        p = l.find_element_by_xpath(
                            '..').find_element_by_xpath('..')
                        sb2 = p.get_attribute('id')
                        if sb in sb2:
                            link = l
                            break
                else:
                    link = browser.find_element_by_link_text(
                        data['search_day'])
                link.click()
                self._set('msg_user', 'Pausa 5 segundos. DEBUG 11...', True)
                self.util.sleep(5) # pausa forzada o se desconecta
                browser.find_element_by_id(self.g.SAT['submit']).click()
                self.util.sleep(sec)
            elif data['type_invoice'] == 2 and data['sat_month']:
                self.util.sleep(2) #ok, aqui no he entrado (creo)
                return self._download_sat_month(data, browser)
            #''' #el día de hoy 2015.02.03 no funciona sin este codigo
            try:
                self.util.sleep(3) #mrE
                found = True
```

Es curioso el cambio funciono toda la mañana, pero fallo cerca del mediodia, es casi seguro que el tiempo en las pausas es critico y dependen de lo lento del "internet", en nuestro caso se comparte entre muchos usuarios.

**Comment by pixelead0** [comment]
Hola @mr-E  yo he descargado sin problema las facturas emitidas y recibidas. 
Con la última modificación que agregó @mauriciobaeza en el select de la fecha.

No entiendo del todo cual la falla que reportas.

**Comment by mr-E** [comment]
De hecho el codigo original si funciona. 
Pero en mi caso, descubrí que debo de añadir ciertas pausas y aumentar el tiempo de otras, entre el primer clic de la seleccion-busqueda del día y la segunda vez que vuelve a seleccionar-buscar.
La verdad no se que factores hacen que un día funcione sin el codigo "bug del SAT" y otros dias sin este no funciona es extraño. Con mis cambios me ha estado funcionando, solo que aun no logro determinar los "tiempos" menos tardados.
Otra, recibimos cientos de comprobantes diario, y no funciona la descarga mensual.. ojala que no recibamos +500 en un día porque ya no vamos a poder descargar ese día con esta aplicación (en este momento). Si llegase a ocurrir, voy a necesitar indicar la hora para estos casos y continuar a partir del ultimo recibo del día. Detallitos.

**Comment by ghost** [comment]
No son detalles, son tonterias del SAT... si no hay nada más que agregar, ¿podemos cerrar este tema?

Saludos

**Comment by ghost** [comment]
Cerramos al no ser un problema del sistema si no del SAT
