### ISSUE TITLE
Febrero 12 - el SAT no muestra ningun comprobante

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#18]
Esta no es falla de la aplicación pero es un caso que no habia visto desde que uso esta aplicación.

Se que hay comprobantes para nuestro receptor, porque al menos hemos recibido un correo con un comprobante con fecha de hoy 12 de febrero. Pero el SAT no lo muestra (en su portal ni con la aplicación), es más no muestra ni los comprobantes que hemos generado nosotros. Pude descargar los dias 10 y 11, pero durante varios intentos en este día ninguno del dia 12.

Ojala que sea un evento "esporadico" y que no se vaya a eliminar este servicio que apuntaba a ser útil.
"Sueños guajiros" ojala el SAT implemente un web service para descargar los comprobantes, seria genial.

Duda: ¿Porque no puedo añadir flags?

**Comment by linuxman** [comment]
Por un momento creí que era problema de la aplicación, pero ya veo que no, al parecer el SAT no esta pudiendo con la carga.

Al igual que mr-E no logro completar descargas del mes de febrero, a veces si, a veces no, el servicio esta muy errático y ante el menor problema la aplicación se cierra.

¿A ustedes les pasa lo mismo?

**Comment by ghost** [comment]
Tal vez no tengas permisos para agregar etiquetas...

Apenas antier le descargue a mi novia todo 2014 y Enero 2015 sin problemas... pero si, esto depende totalmente de la red del SAT... ahora pruebo con Febrero y les cuento...

**Comment by linuxman** [comment]
Descargué un día de enero y sin problemas, pero febrero es muy variable. A ver como te va Mauricio y comentas please :)

**Comment by ghost** [comment]
![screenshot from 2015-02-27 18 04 44](https://cloud.githubusercontent.com/assets/636253/6423414/5150db6e-beab-11e4-9f2e-d996186d824c.png)

al principio no queria ni abrir la página de identificación, después de varios intento descargue febrero sin problemas...

**Comment by ghost** [comment]
Por si no lo han notado, publicamos Admin-CFDI 0.2.6

**Comment by linuxman** [comment]
No lo había notado!!!, en este momento lo descargo !!!.

Viendo tu screenshot 213 archivos es un mes es una nada para lo que manejamos aquí, pero ya me diste respuesta, es cosa del SAT. :/ yo no se para que ofrecen un servicio que no pueden sostener.

Saludos !!!

**Comment by ghost** [comment]
Puedes intentar descargar por día solamente... también esta planeado dejar el admin-cfdi en segundo plano, para que intente descargar hasta que la página del SAT se le antoje funcionar...

creo que podemos cerrar este tema, ¿verdad?

**Comment by linuxman** [comment]
Supongo que si.. y es que el mayor problema es el origen de la información... no se porque no se le ocurre al SAT ofrecer la opción de descargar todos archivos de una consulta en formato zip... creo que sería mucho más rápido ¿no creen?

**Comment by ghost** [comment]
quiero pensar que hay muchas razones (atenuantes) por las que esta diseñado así, solo que no se me ocurre ninguna... jejeje...

también es bueno procurar que el proveedor sea el que te entregue el documento, a fin de cuentas es su responsabilidad, admin-cfdi tiene soporte para descargar de correos directamente...

hay una propuesta en el aire con la posibilidad de formar un frente común para ir al SAT a exponer las problematicas diarias para la administración de los XML, lo estaremos anunciando por aquí, esten al pendiente para que se sumen...

Un abrazo

**Comment by ghost** [comment]
Cerramos al no ser un problema del sistema si no del SAT
