### ISSUE TITLE
Separar las funciones de descarga

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#25]
Para el punto 1. de la [reunión de 2015-02-25](https://github.com/LinuxCabal/admin-cfdi/wiki/Reuni%C3%B3n-2015-02-25), se propone agregar en [pyutil.py](https://github.com/LinuxCabal/admin-cfdi/blob/master/pyutil.py) una nueva clase que incluya las dos funciones _download_sat()_ y _download_sat_month()_  existentes en admin-cfdi.py:

```
class DescargaSAT(object):

    def __init__(self, data, progress_callback=print):
        ...

    def download_sat(self):
        ...

    def download_sat_month(self):
        ...
```

Un script utilizaría la descarga así:

```
descarga = pyutil.DescargaSAT(data)
descarga.download_sat()
```

Los textos de avance irán a stdout del script.   Opcionalmente el script puede usar progress_callback para anotar el tiempo de cada avance y obtener métricas.

admin-cfdi.py la usaría con el segundo parámetro, para que los textos de avance aparezcan en la interfase gráfica como lo hacen ahora:

```
class Application(pygubu.TkApplication):
    ...

    def msg_user(self, msg):
        self._set('msg_user', msg, True)

    def button_download_sat_click(self):
       ...
       descarga = pyutil.DescargaSAT(data, progress_callback=msg_user)
       descarga.download_sat()
```

¿Tienen alguna sugerencia, qué más hay que incluir o algo a modificar? Una vez de acuerdo con la definición, lo que sigue será:
1. Crear pruebas unitarias e,implementar
2. Crear una o más pruebas funcionales
3. Usar en admin-cfdi.py y remover las funciones ya existentes
4. Probar explicit waits y otras mejoras, comparando las métricas obtenidas de pruebas mediante script.

**Comment by ghost** [comment]
Tal vez podríamos considerar en este paso, tener dos opciones de descargar:

1.- Una visual usando selenium
2.- Otra solo script para usarse por ejemplo en un servidor...

**Comment by ppaez** [comment]
Hola, ya tenemos un cierto avance en este issue.  Si alguien quiere y tiene tiempo de probar **descarga.py**, me gustaría saber sus comentarios.  Espero que les guste, a mí me agradó descargar CFDIs desde la línea de comando en bash :)  Hay que hacer pull de la rama separar-download-sat en [mi fork del proyecto](https://github.com/ppaez/admin-cfdi.git), es en donde se ha estado trabajando.

**Comment by ppaez** [comment]
La separación está completa, la rama separar-descarga-sat se mezcló en develop.  Mejoras subsecuentes en DescargaSAT se harán en otro issue nuevo.
