### ISSUE TITLE
Organiza xml ignora archivos con nombre en mayúsculas

### ISSUE THREAD

**Issue by arksega** [LinuxCabal/admin-cfdi#27]
Al organizar los xml, si los archivos tienen la extensión en mayúsculas, son ignorados.

**Comment by ghost** [comment]
Recuerdo haberlo considerado, pero en mis pruebas, por alguna razón se quedo fuera, solo que ahora no recuerdo por que?...

**Comment by ppaez** [comment]
La solución implementada por @arksega en #30 ha sido mezclada en la rama develop
