### ISSUE TITLE
¿fallo con version 36 de firefox?

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#28]
Se me actualizo Firefox a la versión 36 la semana pasada.

Y me comentan que desde el sabado no funciona la aplicación, abre firefox pero no se ve que intente logearse. Ya lo comprobe en mi equipo tengo todo el dpia intentando cada hora aprox.

¿Alguien puede corroborar esta falla o solo es de nuestro lado?
¿Quizas cambio la url donde se debe de logear el contribuyente?

**Comment by ppaez** [comment]
¿Qué versión de webdriver tienen? Hay este [bug](http://code.google.com/p/selenium/issues/detail?id=8399) en webdriver 2.44 con Firefox 36.  Se corrigió en 2.45.  Para saber la versión de webdriver:

```
  python3 -c 'from selenium import webdriver ;print(webdriver.__version__)'
```

**Comment by mr-E** [comment]
Donde tengo problemas seguro es la version 2.44, :) mañana (sDq) es lo primero que actualizare.
Gracias Patricio!

**Comment by ppaez** [comment]
En #29 @mr-E menciona que se actualizón Selenium y ya se descargan los CFDIs, cerramos este issue.
