### ISSUE TITLE
¿No se descargan los cancelados?

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#29]
Recuerdo que en dias pasados se descargaban los xml activos e incluso los cancelados, ya que una vez descargados los proceso uno a uno, compruebo su vigencia y los registro en una BD con su estatus (activo, cancelado, no encontrado).

Aunque sospecho que un comprobante lo pude descargar activo y cuando los procese días despúes, seguro lo cancelaron (esa seria una explicación).

Lo comento porque el día de hoy, una vez actualizado selenium, la aplicación me indica 142 comprobantes en feb-27, pero solo descarga 140, despues de mucho probar hice una lista de uuids (guarde cada pagina de ese dia) la ordene y la compare con el listado de la carpeta ordenados por uuid en una hoja de calculo. Y detecté que los faltantes son dos comprobantes cancelados.

Luego intente descargar cada uno por el uuid desde la aplicación, y aunque lo encuentra y todo, no lo descarga.

A nosotros nos conviene tener los xmls activos y cancelados, es muy conveniente para saber detectar si pagamos algo que luego nos cancele el proveedor. Porque ese es el gran problema que cancelen despues de haber pagado, (ya me imagino el siguiente "parche" del sat para prevenir esto: ¿comprobantes por pagos?).

**Comment by ghost** [comment]
Como ya te diste cuenta, los cancelados ya no están disponibles, pero si los descargaste previamente, desde al mismo Admin-CFDI puedes validar el estatus actual del SAT, no necesitas volver a descargar...

Por otra parte, la descargar SAT es solo un apoyo, los documentos XML que nos generan, los proveedores están obligados a proporcionartelos, me parece un error tomar al SAT y su pesima página como fuente primaria...

Saludos

**Comment by mr-E** [comment]
Ah estimado Mauricio, sin palabras (bueno, unas cuantas...)
Parece un error confiar en el portal, pero si vieras la cantidad de errores que se podrían ahorrar solo si el portal fuera 100% confiable.
Entre los errores del portal y los otros cientos de errores de los proveedores que: envian, no envian, o traen errores hasta del RFC... este portal seria el primer y mejor filtro antes de nada.
