### ISSUE TITLE
[Generar PDF] Plantilla JSON.

### ISSUE THREAD

**Issue by pixelead0** [LinuxCabal/admin-cfdi#3]
¿Como funciona la opcion JSON, dentro de la pestaña de generar PDF?

**Comment by ghost** [comment]
Esta en desarrollo... pero hará eso, desde un archivo JSON generará el PDF, para no depender de LibreOffice...

**Comment by ghost** [comment]
Se ha agregado soporte para plantilas CSV en vez de JSON...
