### ISSUE TITLE
Usabilidad de descarga.py

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#31]
En la [reunión de 2015-03-04](https://pad.riseup.net/p/pythoncabal-20150304) se hicieron sugerencias de mejoras:
1.  Renombrar archivo predeterminado pwd -a credenciales o **credenciales.conf**
2.  Agregar  **--solicitar-credenciales** que pregunte las credenciales al inicio
3. Cambiar --mes-completo por **--mes-completo-por-dia** para evitar ambigüedad
4. --carpeta-destino que su valor por omisión sea **~/cfdi-descarga**

Si hay más sugerencias, por favor comenten para tomarlas en cuenta.

**Comment by mr-E** [comment]
Ofuscar la clave en el archivo ui\config.ini usando el RFC; para evitar "mirones" a la clave.
Mañana pongo un ejemplo, no lo programe para que se guarde al escribir los datos pero seria cosa de ofuscar al guardar el archivo config.ini y al leerlo desofucar usando el mismo RFC.
En mi caso tengo usuarios bastante curiosos y asi evitamos que por "equivocacion" entren y cancelen facturas emitidas (no recuerdo si para cancelar pide el cer/key pero un seguro mas no hace daño).

**Comment by mr-E** [comment]
Ofuscar la clave en el archivo ui\config.ini usando el RFC; para evitar "mirones" a la clave.
Mañana pongo un ejemplo, no lo programe para que se guarde al escribir los datos pero seria cosa de ofuscar al guardar el archivo config.ini y al leerlo desofucar usando el mismo RFC.
En mi caso tengo usuarios bastante curiosos y asi evitamos que por "equivocacion" entren y cancelen facturas emitidas (no recuerdo si para cancelar pide el cer/key pero un seguro mas no hace daño).

**Comment by mimex** [comment]
Si, aunque me parece mejor idea cifrar la clave con GPG.

**Comment by mr-E** [comment]
Si seria algo ideal, solo que tuve que hacerlo de urgencia para poner a un usuario a descargar y no quise dejar la llave a la vista.
Total que en admincfdi.py tengo esto:

``` python
# deofuscate configuracion
self.users_sat[k]['razon_social'] = base64.b64decode(self.users_sat[k]['razon_social'].encode('utf-8')).decode(encoding='ascii')
self.users_sat[k]['password'] = base64.b64decode(self.users_sat[k]['password'].encode('utf-8')).decode(encoding='ascii')
self.users_sat[k]['user_sat'] = base64.b64decode(self.users_sat[k]['user_sat'].encode('utf-8')).decode(encoding='ascii')
```

Poco elegante pero funcional.
Ejemplo como los ofusque, luego los pegue al archivo config.ini

``` python
import base64
data = {
    "contribuyentes": {
        "XAXX010101000": {
            "user_sat": "XAXX010101000", 
            "target_sat": "/home/mrE/virt/cfdadmin/almacen", 
            "razon_social": "[Razon Social]", 
            "password": "LaClave!"
        }
    }
}    
#
print (data["contribuyentes"]["XAXX010101000"])
print('-'*33)
raw_pw = data["contribuyentes"]["XAXX010101000"]["user_sat"].encode('utf-8')
# Encode password
encoded_pw = base64.b64encode(raw_pw)
# Decode password
decoded_pw = base64.b64decode(encoded_pw)

print(encoded_pw, decoded_pw)
print(encoded_pw.decode(encoding='ascii'), decoded_pw.decode(encoding='ascii'))
print('.'*33)
#-----------------------------------------------------
raw_pw = data["contribuyentes"]["XAXX010101000"]["password"].encode('utf-8')
# Encode password
encoded_pw = base64.b64encode(raw_pw)
# Decode password
decoded_pw = base64.b64decode(encoded_pw)

print(encoded_pw, decoded_pw)
print(encoded_pw.decode(encoding='ascii'), decoded_pw.decode(encoding='ascii'))
print('.'*33)
#-----------------------------------------------------
raw_pw = data["contribuyentes"]["XAXX010101000"]["razon_social"].encode('utf-8')
# Encode password
encoded_pw = base64.b64encode(raw_pw)
# Decode password
decoded_pw = base64.b64decode(encoded_pw)

print(encoded_pw, decoded_pw)
print(encoded_pw.decode(encoding='ascii'), decoded_pw.decode(encoding='ascii'))
```

Esto genera las siguiente salida:

``` code
{'user_sat': 'XAXX010101000', 'target_sat': '/home/mrE/virt/cfdadmin/almacen', 'razon_social': '[Razon Social]', 'password': 'LaClave!'}
---------------------------------
('WEFYWDAxMDEwMTAwMA==', 'XAXX010101000')
(u'WEFYWDAxMDEwMTAwMA==', u'XAXX010101000')
.................................
('TGFDbGF2ZSE=', 'LaClave!')
(u'TGFDbGF2ZSE=', u'LaClave!')
.................................
('W1Jhem9uIFNvY2lhbF0=', '[Razon Social]')
(u'W1Jhem9uIFNvY2lhbF0=', u'[Razon Social]')
```

**Comment by ppaez** [comment]
@mr-E Sí hace falta que las credenciales no estén en texto, y concuerdo con @mimex en que la solución debería ser encriptar.  Este tema aplica tanto para descarga.py, que usa credenciales.conf, como para admincfdi.py en su ui/config.ini ¿Les parece si abrimos un issue nuevo llamado "Encriptar las credenciales" en donde analicemos las opciones y definamos cual opción y cómo implementarla?

**Comment by ppaez** [comment]
Ya están agregadas las sugerencias de la 1. a la 4. que se listan al principio :)  Si tienen oportunidad de revisar los commits en #32 o usarlas y comentar, estaría bien para saber como vamos.  Buen fin de semana!

**Comment by ppaez** [comment]
El pull request #32 ha sido mezclado en la rama develop.  Se sugiere crear un nuevo issue para la sugerencia de @mr-E de encriptar el archivo de credenciales.

**Comment by mimex** [comment]
+1 a crear un nuevo issue para lo del cifrado, hay que buscar que los
issues traten un solo tema :)

**Comment by ghost** [comment]
Supongo que como comenta @mr-E, es solo para usuarios curiosos, a fin de cuentas, tener el método de ofuscar dentro del código no ayuda mucho para alguien **más** curioso...
