### ISSUE TITLE
Refactorizar DescargaSAT

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#33]
Se están agregando los parámetros individuales en lugar de pasar data, y se crean pruebas funcionales.  El avance está en esta rama [refactorizar-DescargaDAT](https://github.com/ppaez/admin-cfdi/commits/refactorizar-DescargaSat) en mi fork del repositorio.

**Comment by ppaez** [comment]
Así es como se muestra en la consola cuando se corren las pruebas funcionales en Debian testing con Python 3.4.2:

```
(env34) pp@mc:~/admin-cfdi$ py functional_DescargaSAT.py -v
test_año_mes_día (__main__.DescargaSAT) ... ok
test_mes_completo (__main__.DescargaSAT) ... ok
test_rfc (__main__.DescargaSAT) ... ok
test_uuid (__main__.DescargaSAT) ... ok

----------------------------------------------------------------------
Ran 4 tests in 254.376s
```

**Comment by ppaez** [comment]
Ayer comentamos Sergio y yo en LinuxCabal sobre dividir _download_sat() actual en cada uno de los pasos, con lo que la clase quedaría así:

```
class DescargaSAT(object):

    def __init__(self, status_callback=print, download_callback=print):

    def connect(rfc='', ciec='', archivo_credenciales='',
                solicitar_credenciales=False)

    def search(año=None, día=None, mes=None,
               facturas_emitidas=False,
               uuid='',
               rfc_emisor='',
               mes_completo_por_día=False):

    def download(carpeta_destino=''):

    def disconnect()
```

Con esto se puede lanzar el navegador y hacer login una vez, uno o más varias búsquedas, y finalmente cerrar sesión y apagar el naegador.  Además simplifica la creación de las pruebas unitarias.

**Comment by mimex** [comment]
+1 a la propuesta de separar en funciones mas pequeñas

**Comment by ppaez** [comment]
Los cambios para esta propuesta ya se mezclaron, y la documentación correspondiente se está proponiendo en #48
