### ISSUE TITLE
Descargar xml mediante peticiones HTTP

### ISSUE THREAD

**Issue by jjlopez** [LinuxCabal/admin-cfdi#34]
Hola a todos.

Desde hace un par de semanas he estado trabajando en una librería para descargar los xml del servicio del SAT mediante peticiones HTTP utilizando Requests(http://docs.python-requests.org/en/latest/), pensando en que se pueda integrar a admin-cfdi esta nueva funcionalidad. 

El estado actual del desarrollo es que ya se puede realizar la descarga de los CFDI filtrando por fecha.

La dirección del repositorio es la siguiente:
https://github.com/jjlopez/descargar-cfdi

Cualquier sugerencia es bienvenida.

¡Saludos a todos!

**Comment by mr-E** [comment]
Gracias por el aviso. No he probado tu proyecto aún.
Pero me surge esta duda (la cual puede aplicar incluso en admin-cfdi):

¿Es posible añadir como parametro la hora inicial/final del día a descargar? Esto porque a como van las cosas, pronto llegaremos a recibir +500 comprobantes diarios. Y seria muy útil el poder indicar el rango de horas (inicial y final) para descargar en dos partes cuando se tienen +500 comprobantes.

La razón de recibir tantos: "los viaticos de repartidores cuando compran en esa tiendita que invadio todo mexico".

**Comment by jjlopez** [comment]
Si es posible con el método descargarPorFiltros. 

Mira este ejemplo.

Descargar los xml del día 16/02/2015 que tengan la hora de creación entre las 15:10:07 y las 22:14:10 horas

``` python
from ServicioCfdi import ServicioCfdi
from FiltrosRecibidos import FiltrosRecibidos

servicio = ServicioCfdi('RFC', 'Contrasena')
#Definir filtros personalizados
filtros=FiltrosRecibidos()
filtros.annio='2015'
filtros.mes='2'
filtros.dia='16'
filtros.horaInicial='15'
filtros.minutoInicial='10'
filtros.segundoInicial='7'
filtros.horaFinal='22'
filtros.minutoFinal='14'
filtros.segundoFinal='10'

if not servicio.descargarPorFiltros('/home/usuario/xml/', filtros):
    print("Ha ocurrido el siguiente error: " + servicio.obtieneMensajeError())
else:
    descargados = servicio.obtieneListaDocumentosDescargados()
    print("XML Descargados: " + str(len(descargados)))
```

¡Saludos!

**Comment by mr-E** [comment]
Gracias!

**Comment by ppaez** [comment]
Prueba exitosa en debian testing + Python 3.4.2 +  requests 2.5.3 y 2.6.0 + descargaPorFiltros, usando solo año y mes:

```
(env34) pp@g6:~/descargar-cfdi$ pip freeze
lxml==3.4.2
requests==2.5.3
(env34) pp@g6:~/descargar-cfdi$ ./descarga_filtros.py 
XML Descargados: 14
(env34) pp@g6:~/descargar-cfdi$ pip install -U requests
Downloading/unpacking requests from https://pypi.python.org/packages/py2.py3/r/requests/requests-2.6.0-py2.py3-none-any.whl#md5=3ab1972bbaf2802d94516fb86b9b0d0b
  Downloading requests-2.6.0-py2.py3-none-any.whl (469kB): 469kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.5.3
    Uninstalling requests:
      Successfully uninstalled requests
Successfully installed requests
Cleaning up...
(env34) pp@g6:~/descargar-cfdi$ ./descarga_filtros.py 
XML Descargados: 14
```

Ví el error que reporta Omar en la lista, pero no logro reproducirlo :(

**Comment by omar7c1** [comment]
Mi error estaba en un problema con la Wifi, el error sucede cuando no encuentra la coneccion con el host. ahora esta funcionando estoy por subir una nueva clase para agregar la funcion de acomodar los xmls descargados de forma facil 

Saludos

**Comment by omar7c1** [comment]
Agrege una nueva clase para acomodar los XMLs por carpetas: https://github.com/omar7c1/descargar-cfdi/blob/master/AcomodaXML.py

Les dejo un ejemplo de como acomodar las carpetas de forma automatica

<pre>
#!/usr/bin/env python
import os
#Acomodando archivos
from AcomodaXML import AcomodaXML
servicio = AcomodaXML('/home/omar/git/descargar-cfdi/test/', '/home/omar/git/descargar-cfdi/test2/')
servicio.ordenar("@receptorRFC@-@receptorNombre@"+os.sep+"@ano@"+os.sep+"@mes@"+os.sep+"@emisorRFC@-@emisorNombre@"+os.sep+"@UUID@.xml")
</pre>

**Comment by ghost** [comment]
Si pueden ayudar a probar esta rama: 
https://github.com/jjlopez/admin-cfdi/tree/feature/requestRecibidas

**Comment by jjlopez** [comment]
En estos momentos en la rama https://github.com/jjlopez/admin-cfdi/tree/feature/requestRecibidas solo funciona la descarga por UUID y para probar es necesario agregar al PYTHONPATH la ruta absoluta del directorio "admin-cfdi/admincfdi/descargarcfdi/".

**Comment by suuperjeivier** [comment]
Disculpen una pregunta como resolvieron esta sección del código, si alguien pudiera explicarme con palabras entendibles ya que en la primera versión del programa hacen mención del atributo sb y ahora solo el id o.o. https://github.com/LinuxCabal/admin-cfdi/blob/develop/admincfdi/pyutil.py#L1875-L1886

**Comment by ghost** [comment]
Si están de acuerdo ponemos esta característica para 0.4...

Podemos poner que sea opcional, con interfaz gráfica usando selenium o sin interfaz usando esto.

**Comment by ppaez** [comment]
@jjlopez Hola Jonathan, en la interfaz gráfica de admin-cfdi tenemos un renglón de status, en donde aparecen los pasos en los que va la descarga, also similar a esto:

```
   Conectando...
   Conectado...
   Buscando...
   Factura 1 de 13
   Factura 2 de 13
   Factura 3 de 13
   Factura 4 de 13
   Factura 5 de 13
   Factura 6 de 13
   Factura 7 de 13
   Factura 8 de 13
   Factura 9 de 13
   Factura 10 de 13
   Factura 11 de 13
   Factura 12 de 13
   Factura 13 de 13
   Desconectando...
   Desconectado..
```

En  admincfdi/pyutil.DescargaSat que usa Firefox/Selenium, definimos un callback, el cual es llamado en cada paso general donde se da un status, y un segundo callback que es específico para una barra de progreso durante el ciclo de descarga de cada factura:

https://github.com/LinuxCabal/admin-cfdi/blob/master/admincfdi/pyutil.py#L1734

Con estos callbacks se actualizan la línea de status y la barra de progreso en la interfaz gráfica.

En la biblioteca estándar de Python , el módulo ftplib usa este mecanismo en algunas de las funciones que pueden tardar, para poder indicar a la aplicación el progreso.  Su uso es opcional en casi todas las funciones que lo tienen:

https://docs.python.org/3/library/ftplib.html#ftplib.FTP.retrbinary

¿Cómo te parecería el agregar estos dos callbacks de status y progreso a tu módulo?   Igual si tienes otras sugerencias de cómo podríamos hacerle, estaría bien comentarlas aquí.

**Comment by ghost** [comment]
Que por cierto no veo que se muestre en Windows, en Linux si se ve el cambio de mensaje, pero en Windows no veo que refresque... ¿alguien puede confirmar?...

Es probable que sea un problema de pygubu...

**Comment by jjlopez** [comment]
Hola a todos.

@ppaez Voy a revisar la información que me enviaste y cualquier duda se las hago saber.

Saludos!

**Comment by ghost** [comment]
Pongo a su consideración la siguiente rama: https://github.com/UniversoLibreMexicoAC/descargar-cfdi/tree/script

Esta basada en el extraordinario trabajo de Jonathan...

esta pensada para integrarse más tarde en Admin-CFDI...
aunque se puede usar como script independiente para agregarse a un cron por ejemplo...

He eliminado la dependencia de lxml, ya que se usaba solo en dos pequeñas partes. Esto permite también integrarla en extensiones de LibreOffice por ejemplo.

Saludos

**Comment by ghost** [comment]
Creo que esta casi listo: https://github.com/UniversoLibreMexicoAC/descargar-cfdi/tree/script
- Ahora hace la descarga automática de más de 500 al mes...
- Ahora se guarda la lista de documentos previamente descargados, con lo que las descargas posteriores son más rápidas al descargar solo los faltantes...
- La descarga se segmenta en hilos, pude descargar casi 900 documentos en poco más de 3 minutos en mi lamentable conexión de 1 MB

Me falta validar cuando hay más de 500 en un día... si alguien recibe esta cantidad de documentos, muy bien puede financiar esta ultima parte...

Saludos

**Comment by echeverrifm** [comment]
Hola a todos

Solo me descarga las facturas recibidas, quiero obtener las facturas emitidas y los recibos de nominas emitidos.

Hay algun filtro?

Saludos y muy buen proyecto

**Comment by ghost** [comment]
Todo lo que quieres ya lo hace en esta otra rama: https://github.com/UniversoLibreMexicoAC/descargar-cfdi

Saludos

**Comment by echeverrifm** [comment]
Esto que me pasaron solo funciona en Python 3.0, no hay algo en 2.7

Saludos

**Comment by ghost** [comment]
Solo PY3, creo que sería trivial pasarlo a 2.7, pero... esa es tu tarea...

**Comment by cyberfrentic** [comment]
Hola quiza sea antiguo el post, primero que nada agradecer por el aporte es fantastico, pero alguien tiene alguna clase que descargue masivamente las facturas emitidas, alguien podria ayudartme

**Comment by ghost** [comment]
Este código descarga emitidas y recibidas...

pero... el SAT acaba de agregar captcha a la descarga masiva, por ahora, ninguna herramienta te funcionará...

**Comment by cyberfrentic** [comment]
chispas!!!... y ahora?? ya valio? y yo que andaba iniciando en eso... jajajaja.. alguien que sepa como y pueda ayudar? y en cuanto? $$$$

**Comment by ghost** [comment]
estamos trabajando en ello...

**Comment by cyberfrentic** [comment]
muchas gracias mauriciobaeza, agradeceria mucho la ayuda que pudieras proporcionar, ya que inicio en el mundo de python y me parece atractivo el uso de este lenguaje para la imprementacion de cfdi, lastima que el SAT haga tanto movimeintos y actualizaciones..

**Comment by MauricioMarz** [comment]
Mauricio, creo que tengo una opción que les puede ayudar, el truco esta en hacer login desde aquí: 

https://cfdiau.sat.gob.mx/nidp/jsp/content.jsp?id=mat-ptsc-cont&sid=0
Esta opción no tiene captcha..
Después de el login, redirigir a 
https://portalcfdi.facturaelectronica.sat.gob.mx
saludos

**Comment by ghost** [comment]
Hola...

Gracias, si, ya tenemos esa liga trabajando... por aquí: https://gitlab.com/mauriciobaeza/cfdi-descarga

en la rama captcha de ese repositiorio, ya te muestra el captcha, lo capturas y sigue la descarga normal, por si nos quitan en algun momento la liga indicada...

por otra parte, ya estoy trabajando en una versión que usa la FIEL.

Saludos

**Comment by leti2104** [comment]
hola @mauriciobaeza  etsba checando la ultima actualizacion que hiciste donde ya trabajaste con el captcha pero tengo un error cuando ejecuto el siguiente comando
leticia@lety:~/cfdi/source$ sudo fades cfdi-descarga.py -bd 
Traceback (most recent call last):
  File "cfdi-descarga.py", line 25, in <module>
    from sat.util import validate_rfc, sat_download, join, validate_folder, today, \
  File "/home/leticia/cfdi/source/sat/util.py", line 23, in <module>
    from .portal_sat import PortalSAT
  File "/home/leticia/cfdi/source/sat/portal_sat.py", line 25, in <module>
    from . import captcha
  File "/home/leticia/cfdi/source/sat/captcha.py", line 31, in <module>
    class DlgCaptcha(QTW.QDialog):
NameError: name 'QTW' is not defined
cres tener una sugerencia

**Comment by pixelead0** [comment]
@leti2104 más información sobre tu sistema operativo, version de python. 
en linux Mint, me salia un error similar, hasta que me di cuenta que por default el sistema considera  python2.7 en lugar de python3.

**Comment by ghost** [comment]
Varias sugerencias:

Usen el sistema del proyecto para reportar errores: https://gitlab.com/mauriciobaeza/cfdi-descarga, NO en Github por favor...

¿te aseguraste de instalar pyqt5?

Si usas fades No uses sudo, de hecho, solo debes de usarlo si instalar las dependencias en tu distribucion, despues, NO deberias usar sudo.

Saludos

**Comment by leti2104** [comment]
@mauriciobaeza  si ya esta instalado pyqt5 pero sigue saliendo este error
Traceback (most recent call last):
  File "cfdi-descarga.py", line 25, in <module>
    from sat.util import validate_rfc, sat_download, join, validate_folder, today, \
  File "/home/leticia/fades_Cfdi/cfdi-descarga/source/sat/util.py", line 23, in <module>
    from .portal_sat import PortalSAT
  File "/home/leticia/fades_Cfdi/cfdi-descarga/source/sat/portal_sat.py", line 25, in <module>
    from . import captcha
  File "/home/leticia/fades_Cfdi/cfdi-descarga/source/sat/captcha.py", line 31, in <module>
    class DlgCaptcha(QTW.QDialog):
NameError: name 'QTW' is not defined
 y disculpa por molestar pero quiero entender bien lo que haces es para un trabajo de la escuela y casi no hay informacion del uso de fades

**Comment by ghost** [comment]
Por favor, publica esto en el repositorio del proyecto...

He actualizado las dependencias necesarias para fades, es indispensable tener pip y setuptools correctamente instalado, para que fades pueda instalar las dependencias.

Mira el wiki y sigue los pasos: https://gitlab.com/mauriciobaeza/cfdi-descarga/wikis/home

Reitero, NO reponderé más preguntas en este hilo, agradezco su comprensión.

**Comment by fritssalcedo** [comment]
alguien sabe que paso que ya no descarga los archivos de la sat, ni emitidos ni recibidos
