### ISSUE TITLE
Problemas al generar PDF con información aduanera

### ISSUE THREAD

**Issue by mimex** [LinuxCabal/admin-cfdi#35]
En la pestaña "Generar PDF" se omiten las facturas con "Información Aduanera" cuando no definen el campo "Aduana" (que de acuerdo al [cfdv32.xsd](http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv32.xsd) es opcional):

```
<cfdi:Concepto cantidad="1" unidad="pz" descripcion="EJEMPLO 1" valorUnitario="990.000000" importe="990.00">
      <cfdi:InformacionAduanera numero="00001" fecha="2015-01-09" />
 </cfdi:Concepto>
```

El mismo concepto pero con el campo aduana funciona sin problemas:

```
<cfdi:Concepto cantidad="1" unidad="pz" descripcion="EJEMPLO 2" valorUnitario="990.000000" importe="990.00">
      <cfdi:InformacionAduanera numero="00001" fecha="2015-01-09" aduana="1234"/>
 </cfdi:Concepto>
```

Estuve revisando el código de pyutil.py para corregir el error pero aún no tengo claro que parte es la que debe modificarse, sigo revisando...

**Comment by ghost** [comment]
Clase CFDIPDF... dos métodos _conceptos y _get_description

```
        n = c.find(self.tree['aduana'])
        if n is not None:
            data += '\nPedimento de Importación No. %s\n' % n.attrib['numero']
            data += 'Aduana: %s, Fecha del pedimento: %s' % (
                n.attrib['aduana'], n.attrib['fecha'])
```

Solo hay que validar si no esta la aduana...

**Comment by mimex** [comment]
Queda resuelto en la versión 0.2.7
