### ISSUE TITLE
¿Han intentado verificar la vigencia de comprobantes con el servicio del SAT?

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#43]
¿Han intentado verificar la vigencia de comprobantes con el servicio del SAT?

En mi caso estuve usando el codigo de mauricio (de las primeras versiones de admin-cfdi) y me fallaba; con este parche ahora si puedo verificar la vigencia del comprobante desde el webservice: https://github.com/pysimplesoap/pysimplesoap/pull/52

**Comment by ghost** [comment]
Tal vez por que yo usaba una versión de pysimplesoap diferente, no la del repositorio...

**Comment by mr-E** [comment]
Tuve el problema con las versiones que instala pip: v1.16 en python +3.2.3 y funcionando en python 2.7.3. (algo que se perdió en python +3 afecto en Linux y Windows)

**Comment by ghost** [comment]
Espero pronto reemplazar pysimplesoap por request, la verdad es que la consulta SAT es demasiado sencilla, podemos eliminar esta dependencia

**Comment by ghost** [comment]
Hola...

Hemos reemplazado el uso de pysimplesoap por request, ganando mucho en velocidad de consulta al SAT...

¿Podrías probar esta funcionalidad con la rama develop para poder cerrar este issue?

Gracias

**Comment by ghost** [comment]
@mr-E  ojala puedas probar la rama develop donde hemos mejorado mucho la consulta SAT

**Comment by ppaez** [comment]
La librería se acutalizó y está trabajando bien.
