### ISSUE TITLE
Documentación

### ISSUE THREAD

**Issue by renich** [LinuxCabal/admin-cfdi#5]
Es necesario tener documentación del proyecto.

Necesitamos:
- Documentación técnica para development.
- Documentación técnica para documentar.
- Documentación para colaboradores de diferentes tipos (técnicos, administrativos, promotores, etc.)
- Lineamientos (no reglas).
- Guía de estilo de codificación.

**Comment by ghost** [comment]
Respecto a la guía de estilo, en la medida de lo posible y cada vez más, trato de aplicar el PEP8, lo cual espero siga cualquier contribución.

Me gusta mucho la idea de documentar otros tipos de colaboración no técnicas que son muy necesarias.

**Comment by renich** [comment]
@mauriciobaeza puse una rama. Chécala a ver qué te parece.

**Comment by ghost** [comment]
Había visto los cambios que hiciste en el README y nos lo veía en la rama master, ahora veo la razón, porque lo hiciste en otra rama, jejej... 

esta muy bien, directo a la rama master si puedes mezclarlo...

Saludos

**Comment by ppaez** [comment]
Lo que había bajo _Cómo colaborar al proyecto_ en la página [Home](https://github.com/LinuxCabal/admin-cfdi/wiki) del wiki, se pasó a su propia página.  Se agregaron secciones Lineamientos de código y de documentación.

Por favor [échenle un vistazo](https://github.com/LinuxCabal/admin-cfdi/wiki/C%C3%B3mo-colaborar-en-este-proyecto) y si ven algo que falte o necesite correciones, adelante con el botón **Edit** :)

**Comment by ghost** [comment]
Agregada la información para colaborar [favor de revisar](https://github.com/LinuxCabal/admin-cfdi/wiki/C%C3%B3mo-colaborar-en-este-proyecto)

Cerramos este tema.
