### ISSUE TITLE
Script admin-cfdi en Windows no se puede relacionar a pythonw.exe

### ISSUE THREAD

**Issue by ghost** [LinuxCabal/admin-cfdi#67]
En Windows, para poder relacionar un archivo para apertura con un programa, el archivo debe tener una extensión, el archivo **admin-cfdi** no la tiene, por lo tanto no se puede relacionar con el ejecutable **pythonw.exe** para abrirse y poder dejar un acceso directo para el usuario final.

**Comment by ppaez** [comment]
Estoy probando la opcion que comentamos en la reunión: crear admin-cfdi.cmd, descarga-cfdi.cmd y cfdi2pdf.cmd, que invoquen el interpretador con el script correspondiente, y agregar los nombres de estos archivos en la lista scripts de setup.py, para que se instalen en la carpeta env/bin/. Por ejemplo el contenido de admin-cfdi.cmd sería:

```
   pyw admin-cfdi
```

pyw se refiere a C:\windows\pyw.exe, que el instalador de Python crea y así no hace falta incluir la versión.

Para descarga-cfd.cmd y cfdi2pdf, como son herramientas de línea de comando sí queremos correr en la consola y pasarle todos los parámetros:

```
   py descarga-cfdi %*

   py cfdi2pdf %*
```

py se refiere a C:\windows\py que también resulta conveniente.  Falta checar si hace falta pasar la ruta absoluta del script para que lo encuentre desde otra carpeta, y definir si admin-cfdi.cmd se desea tambien en otra ubicación además de env/bin, ¿Tal vez un atajo en el escritorio?.
