### ISSUE TITLE
Instalación en ambiente virtual falla

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#7]
Se creó un ambiente virtual de Python 3.3 en Fedora 20, Se instalaron pygubu, selenium y uno.  Al ejecutar admin-cfdi.py da este mensaje: 

```
(pyenv3) pp@g6:~/admin-cfdi$ python admincfdi.py 
Traceback (most recent call last):
  File "admincfdi.py", line 17, in <module>
    from pyutil import Util
  File "/home/pp/admin-cfdi/pyutil.py", line 49, in <module>
    import uno
  File "/home/pp/admin-cfdi/pyenv3/lib/python3.3/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: No module named 'base
```

**Comment by ghost** [comment]
La librería uno, en Linux, se usa para tener acceso al API de LibreOfffice, en Linux Mint de hecho solo esta `uno.py` sin el `__init__.py` que se ve en el error... ¿hay alguna otra librería que se llame igual?

Esta dependencia la podemos eliminar si eliminamos la dependencia de LibreOffice para generar los PDF, la ventaja por supuesto es dejar de depender de un software que requiere una instalación muy específica para funcionar como lo es LibreOffice, la desventaja es dejar de usar una plantlla de Calc para el PDF es muy sencillo para el usuario final.

He estado haciendo unas pruebas con esta librería: https://github.com/eea/odfpy
trabaja bien pero al manipular el XML directamente no se aprovecha el API.

También he usado esta: https://github.com/reingart/pyfpdf
pero requiere una plantilla CSV la cual no es nada amigable para el usuario final aunque el resultado es bastante bueno.

Tal vez podamos seguir usando la plantilla ODS pero sin la dependencia de LibreOffice.

¿Que opinan?

**Comment by ghost** [comment]
En ArchLinux es igual, solo esta `uno.py` no tiene más archivos... ¿como instalaron **uno**? esta librería se instala con LibreOffice...

A mi me gustaría eliminar la dependencia de LibreOffice...

**Comment by mimex** [comment]
+1 a eliminar la dependencia de LibreOffice

**Comment by pixelead0** [comment]
@mauriciobaeza sería interesante saber en que podemos apoyarte para eliminar la dependencia de Libre Office.

**Comment by ghost** [comment]
El primer paso es seleccionar la librería que vamos a usar para generar el PDF...

**Comment by ppaez** [comment]
¡Buenas noticias! Se consiguió ejecutar admin-cfdi en un ambiente virtual de Python 3.4 en Debian testing.  Se necesitan estos pasos:
1. Usar la opción **--egg** de pip para evitar [este error conocido](https://github.com/alejandroautalan/pygubu/issues/15) al instalar pygubu:
   
    pip install --egg pygubu
2. Convertir dos módulos de uno a Python 3:
   
    2to3 -w ~/env34/lib/python3.4/site-packages/uno/{base,helpers}.py
3. Evitar el error **ImportError: No module named 'base'** al importar uno:
   
    PYTHONPATH=~/env34/lib/python3.4/site-packages/uno python admincfdi.py
4. No importar en pyutil.py los módulos de LibreOffice que no estan disponibles en el ambiente virtual.  No es una solución, es solamente una salida para poder correr la aplicación por ahora:

```
diff --git a/pyutil.py b/pyutil.py
index 57698f9..659329a 100644
--- a/pyutil.py
+++ b/pyutil.py
@@ -50,9 +50,9 @@ if sys.platform == WIN:
     from win32com.client import Dispatch
 elif sys.platform == LINUX:
     import uno
-    from com.sun.star.beans import PropertyValue
-    from com.sun.star.beans.PropertyState import DIRECT_VALUE
-    from com.sun.star.awt import Size
+    #from com.sun.star.beans import PropertyValue
+    #from com.sun.star.beans.PropertyState import DIRECT_VALUE
+    #from com.sun.star.awt import Size
```

**Comment by ghost** [comment]
Esto nos indica que definitivamente tenemos que eliminar la dependencia de LibreOffice...

**Comment by ppaez** [comment]
Esta es la creación más sencilla del ambiente virtual de Python 3.4 en Debian testing, aprovechando el módulo uno de la distro que ya está instalado con LibreOffice:
1. Crear el ambiente virtual usando los módulos de la distro: pip no se instala :(
   
    pyvenv **--system-site-packages** env34
2. Instalar pygubu y selenium en el ambiente virtual con easy_install de la distro, le proporcionamos con -d la ruta a site-packages en el ambiente virtual y al intérprete le indicamos con PYTHONPATH que ahí busque módulos al importar:
   
    PYTHONPATH=~/env34/lib/python3.4/site-packages/ **easy_install3** -d ~/env34/lib/python3.4/site-packages/ pygubu selenium

¡Listo!

@mauriciobaeza: Concuerdo, mientras tanto esta opción nos resuelve muy bien.

Si alguien más tiene oportunidad de intentar correr admin-cfdi en un ambiente virtual en otra distro, por favor nos comparte cómo le va ;)

**Comment by mr-E** [comment]
``` quote
Ubuntu 14.04
(cfdadmin)mre@pc:~/virt/cfdadmin$ python --version
Python 3.2.3
```

No recuerdo bien, en que partes batalle, esta es la historia:

``` quote
 python3 --version
 virtualenv-3.2 ~/virt/cfdadmin
 source cfdadmin/bin/activate
 pip install selenium pygubu #algo aqui me fallo
 pip install selenium #lo instale uno a uno
 pip install pygubu #se instalaba o no, daba errores
 pip search pygubu
 pip uninstall pygubu
 pip install pygubu
 pip install --egg pygubu #creo que este fue el paso que me ayudo a instalar pygubu
 python admincfdi.py #aqui ya abrio la aplicación
```

**Comment by ppaez** [comment]
Se probó la instalación en ambiente virtual ya con el fix agregado en #41, en Debian testing con Python 3.4 y en Fedora 20 con Python 3.3, sin problema.  Si se desea usar LibreOffice, se puede acceder al módulo uno de la distribución desde el ambiente virtual agregando la ruta del módulo en PYTHONPATH, como nos mostró @arksega en el sprint.
