### ISSUE TITLE
WebFault: Server raised fault: 'Invalid object name 'BitacoraServicioQR20150918'.'

### ISSUE THREAD

**Issue by fedexin40** [LinuxCabal/admin-cfdi#72]
Saludos que tal
Tengo un pequeño problema, lo que pasa es que desde el dia de hoy no puedo validar el cfdi ante el Sat el error que me sale es WebFault: Server raised fault: 'Invalid object name 'BitacoraServicioQR20150918'.' 
No sabra alguien que esta pasando??

**Comment by fedexin40** [comment]
Me contesto solo 
Al parecer el problema es el siguiente
la url que se estaba utilizando era la siguiente `https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?wsdl`

Y cambie la url por la siguiente y funciono todo correctamente `https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc?singleWsdl`

**Comment by ghost** [comment]
Pues la primera ha funcionado bien, hasta ahora... ahora lo revisamos...

**Comment by ghost** [comment]
He verificado y funciona correctamente la consulta, pudos ser una falla temporal del SAT, nada raro con ellos...

cerramos este issue

**Comment by fedexin40** [comment]
Okay muchisimas gracias @mauriciobaeza
