### ISSUE TITLE
No descarga mes completo

### ISSUE THREAD

**Issue by luisfernandobarrera** [LinuxCabal/admin-cfdi#73]
Estoy tratando de descargar un mes y en lugar de descargar las 29 facturas del mes, solo descarga 24.

**Comment by ghost** [comment]
¿podrías dar más detalles de tu entorno de trabajo?... ¿todas los documentos están vigentes?

**Comment by luisfernandobarrera** [comment]
Sí, creo que ya detecté el Bug.

El problema es que cuando el selenium se mete al portal del SAT

Filtra del 1er día del mes al último. Pero las horas son incorrectas, en ambos casos queda a las 00:00:00 cuando en el último día habría que ponerla a las 23:59:59; o mantener la hora y poner en el último día el poner el primer día del mes siguiente a las 00:00 horas.

**Comment by ghost** [comment]
recuerdo que eso ya se arreglo... reviso en cual versión... por eso es muy importante detallar las versiones de trabajo...

**Comment by ghost** [comment]
Esto esta arreglado aquí: https://github.com/LinuxCabal/admin-cfdi/pull/53

**Comment by luisfernandobarrera** [comment]
Estaba revisando el branch master que está al día.

¿En el branch develop solo me deja bajar desde 2014? ¿Quitaron el soporte para antes de 2014?

**Comment by ghost** [comment]
hay una nota en el SAT de que solo aplica a partir del 01 de enero del 2014, pero acabo de hacer una búsqueda de 2012 y 2013 y si me devolvió datos... ahora reviso los años incluidos...

por otra parte, por favor, una pregunta por tema, una respuesta por tema, esto nos permite tener organizado el sistema de reportes de errores. 

Gracias.

**Comment by luisfernandobarrera** [comment]
Ok. Respecto a esto último. La nota del SAT es sobre la búsqueda de facturas filtrada por complementos.

**Comment by ghost** [comment]
ok, proceso a agregar los años anteriores para que quede igual que en el SAT...

Saludos

**Comment by ghost** [comment]
En cuanto se mezcle, creo que podemos cerrar este issue...

**Comment by ghost** [comment]
Se ha mezclado, cerramos este issue.
