### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by sapomuyverde** [LinuxCabal/admin-cfdi#74]
Hola,

Tratando de correr Admin-CFDI, recibo el error:
C:\AdminCFDI_v0.2.2>pythonw admincfdi.py

C:\AdminCFDI_v0.2.2>python admincfdi.py
Traceback (most recent call last):
  File "admincfdi.py", line 17, in <module>
    from pyutil import Util
  File "C:\AdminCFDI_v0.2.2\pyutil.py", line 47, in <module>
    from win32com.client import Dispatch
  File "C:\Users\gabriela\AppData\Local\Programs\Python\Python35\lib\site-packages\win32com__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: %1 no es una aplicación Win32 válida.

Mi entorno es:
Admin-CFDI v0.2.2
Windows 10 64bits
Python 3.5 (x64)

Al intentar con pythonw.exe, como lo recomiendan bajo Windows, no realiza ninguna acción, por eso intenté con python.exe, también me parece que recomiendan la versión 3.4 de python, pero quise hacer pruebas con mi versión actual de python.

Éste error tiene que ver con el requerimiento de la versión de python?, también instalé:
pip install selenium pygubu / pywin32-219.win32-py3.5.

Qué puedo revisar?.

Gracias.

Saludos,
Javier

**Comment by sapomuyverde** [comment]
Hola,

Al parecer había cometido el error de que la instalación de python 3.5 no hacía math con la instalación de pywin32 (32/64 bits).

Saludos,
Javier

**Comment by ghost** [comment]
He probado el funcionamiento en v2.8.0 con py35 y funciona correctamente...

He agregado la validación para cuando no este presente win32 y no de este errror.

En cuanto se mezcle, marcamos como resuelto

Saludos

**Comment by ghost** [comment]
Esta corrección ya esta en la rama develop, si alguien puede validar por favor...

Se puede reproducir en el siguiente escenario:
- Solo en Windows...
- Instalar todo, excepto las extensiones Win32
- Probar que ya no de este error...

Saludos

**Comment by ghost** [comment]
Confirmado, ya no da este error...

**Comment by sapomuyverde** [comment]
Hola Mauricio,

Disculpas, pero no he tenido oportunidad de realizar test, en cuanto logre
tener un espacio lo comento.

Saludos,
Javier

2016-02-04 14:37 GMT-06:00 Mauricio Baeza notifications@github.com:
