### ISSUE TITLE
Error en lectura de credenciales.conf

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#77]
Al correr descarga-cfdi, Firefox se detiene en la pantalla de login del SAT, después se cierra y la aplicación termina.  Reportado al final de #64 por @mauriciobaeza y reproducido.

Varios editores agregan LF (LF CR o CF LF dependiendo del sistema operativo) al final del texto cuando crean un nuevo archivo.  descarga-cfdi y las pruebas funcionales usan readline() para leer la línea del archivo credenciales.conf y descartan el último caracter asumiendo que es LF.  readline() incluye el LF en GNU/Linux, pero no en otros sistemas operativos.

Voy a agregar una función de lectura de credenciales en el módulo pyutil.py, que la usen tanto descarga-cfdi como las pruebas funcionales, que evite este problema y además maneje cuando no existe el archivo o no encuentre los dos valores esperados.  Envío un Pull Request a la rama develop cuando esté listo.

**Comment by ghost** [comment]
Excelente... esperamos para probarlo...

Saludos

**Comment by ghost** [comment]
Corregido y mezclado...
