### ISSUE TITLE
Elemento total en CFDI sin punto decimal

### ISSUE THREAD

**Issue by ppaez** [LinuxCabal/admin-cfdi#79]
`cfdi2pdf` da un error si el valor del elemento total no tiene punto decimal.  ¿Es requisito en los CFDI que este valor tenga punto decimal? Uno de los CFDI con los que hice las pruebas trae subTotal="0", total="0", valorUnitario="0" e importe="0".  Si cambio a total="0.0", el error ya no ocurre.   Parece que el que los otros elementos no tengan decimales no afecta, es solo en total donde se examina cuántos decimales tiene. El traceback es:

``` python
Generando: ../cfdi-descarga/BD73CA92-2684-4672-A782-D4D76A41F0D4.xml
Traceback (most recent call last):
  File "./cfdi2pdf", line 56, in <module>
    main()
  File "./cfdi2pdf", line 50, in main
    pdf = CSVPDF(f, args.plantilla)
  File "/home/pp/admin-cfdi/admincfdi/pyutil.py", line 2073, in __init__
    decimales = len(self.xml.attrib['total'].split('.')[1])
IndexError: list index out of range
```

**Comment by ghost** [comment]
El formato dice hasta seis decimales... pero no dice, sin decimales, todo es cuestión de interpretación... en mi criterio, siempre debería de llevar...

ya se me presento este caso, lo corregí local, lo agrego a la rama para su inclusión...

Saludos

**Comment by ghost** [comment]
Corregido en #81

**Comment by ppaez** [comment]
Gracias!
