### ISSUE TITLE
Ejemplo de "Campos"

### ISSUE THREAD

**Issue by linuxman** [LinuxCabal/admin-cfdi#8]
Mientras se ponen de acuerdo en la documentación, a mi me gustaría saber que es lo que se pone en **Campos** en la sección de **Usuarios y reportes** de la pestaña **Reporte y validación**.

Con un ejemplo es más que suficiente.

**Comment by pixelead0** [comment]
Yo he utilizado los siguientes:

|{fecha}|{emisor_rfc}|{emisor_nombre}|{receptor_rfc}|{receptor_nombre}|{serie}{folio}|{subTotal}|{descuento}|{traslado_iva_0}|{traslado_iva_16}|{totalImpuestosTrasladados}|{retencion_isr}|{retencion_iva}|{totalImpuestosRetenidos}|{total}|{tipoDeComprobante}|{UUID}|

**Comment by ghost** [comment]
El siguiente reporte:

```
{UUID}|{fecha}|{serie}{folio}|{emisor_nombre}|{emisor_rfc}|{receptor_nombre}|{receptor_rfc}|{subTotal}|{traslado_iva_16}|{total}
```

te muestra:

```
UUID    fecha   serie-folio emisor_nombre   emisor_rfc  receptor_nombre receptor_rfc    subTotal    traslado_iva_16 total   Validar XML Validar SAT
0224C8A1-B08C-46DC-AD09-D87DB31E88A4    2015-01-19 16:21:39 TEST182 ACCEM SERVICIOS EMPRESARIALES SC    AAA010101AAA    TGC Ingeniería SA de CV    TIN870407J52    862.07  137.93  1000    Documento válido   No Encontrado
6E4757C2-120E-4217-AF7F-2FDE60816324    2015-01-19 13:38:04 TEST180 ACCEM SERVICIOS EMPRESARIALES SC    AAA010101AAA    TGC Ingeniería SA de CV    TIN870407J52    862.07  137.93  1000    Documento válido   No Encontrado
6A301931-867D-4663-BC4A-17D3C9AC24F8    2015-01-19 16:21:38 NC102   ACCEM SERVICIOS EMPRESARIALES SC    AAA010101AAA    TGC Ingeniería SA de CV    TIN870407J52    862.07  137.93  1000    Documento válido   No Encontrado
```

**Comment by linuxman** [comment]
Excelente, no sabía los detalles de los corchetes o los pipes !!!, con eso tengo para comenzar, aunque sus ejemplos son muy buenos :)

Gracias !!!.
