### ISSUE TITLE
Rama develop en Win 7 y 10

### ISSUE THREAD

**Issue by ghost** [LinuxCabal/admin-cfdi#87]
Con esta rama trabajo muy bien en Linux, pero hoy he intentado descargar desde Win 7 y Win 10 obteniendo el mismo resultado...

En los dos se usa Firefox 44

Abre correctamente la ventana de acceso. Se identifica correctamente. Se queda en la ventana donde dice: se ha identificado correctamente y su sesión será válida 10 minutos. No hace nada más, después de unos momentos se cierra, pero no da ningún error.

¿Alguien puede validar este comportamiento?

Gracias

**Comment by ghost** [comment]
Ya vi el problema, en la línea: https://github.com/LinuxCabal/admin-cfdi/blob/develop/admincfdi/pyutil.py#L1802

Se busca la cadena: "session has been authenticated"

Pero como el sistema esta en español, la leyenda es: "Se ha autenticado su sesión y será válida durante 10 minutos"

Al no encontrarla, da un error de TimeOut...

**Comment by ppaez** [comment]
Estaría bien desligar ese wait del idioma de la página, para evitar problemas si soportamos un solo lenguaje.  Tal vez usar el atributo id o class de ese elemento...

**Comment by ghost** [comment]
Veo que una línea anteror se tiene:

```
 wait.until(EC.title_contains('NetIQ Access'))
```

Esta solo aparece cuando ya se ha identificado... ¿no es suficiente con esta?... esta presente tanto en ingles como en español...

**Comment by ppaez** [comment]
El segundo wait es para asegurar que se carga un iframe, en su contenido se  puede diferenciar si la autentificación tuvo éxito o no, cosa que en este momento no se verifica (ver en la [documentación](http://admin-cfdi.readthedocs.org/es/develop/devel.html#descarga-de-facturas-del-sat).  Creo que falta investigar cómo manejar el pop up que aparece cuando falla la autentificación.

**Comment by ghost** [comment]
Según yo no, mira la siguiente imagen: http://i.imgur.com/xBCYGdo.png

**Comment by ppaez** [comment]
Ah, el título 'NetIQ Access' no aparece cuando falla la autentificación (habrá que actualizar la documentación).  Entonces una opción sin usar el segundo wait, sería más o menos así:

```
from selenium.common.exceptions import TimeoutException
...
try:
    wait.until(EC.title_contains('NetIQ Access'))
    self.status('Conectado')
    return True
except TimeoutException:
    self.status('No conectado')
    return False
```

Cuando la autenticación falla, la página no tiene un elemento title y se da el timeout.

**Comment by ghost** [comment]
Excelente... integrado en #88
