### ISSUE TITLE
Plantilla ejemplo para renombrar XML organizados

### ISSUE THREAD

**Issue by mr-E** [LinuxCabal/admin-cfdi#9]
Quiero usar una plantilla como la siguiente para organizar mejor mis archivos:
{emisor_rfc}_{fecha}_{uuid}_{serie}{folio}

Pero el resultado es muy distinto a lo esperado, me quedan nombres como:
001304_2015-01-12_EJE87052MPLO.xml
CLJ123491161_2015-01-28_EJE87052MPLO.xml
CLJ123491191_2015-01-28_EJE87052MPLO.xml

¿Como debe ser la plantilla para que resulte algo asi?:
CLJ123491161_2015-01-28_40xxx1x-2360-2x6x-9x17-4xx3881558xx_ABC1234xml

Saludos y gracias por la herramienta.

**Comment by ghost** [comment]
El UUID no es un campo válido para esta opción... si la plantilla da un error, se usa la predeterminada... quita el campo UUID y veras el resultado correcto...

Saludos

**Comment by mr-E** [comment]
wow! Gracias mil de antemano por la paciencia de este post: 

Curiosamente hemos recibido varios comprobantes del mismo emisor, con la misma fecha y sin "serie-folio", claro vienen con diferente "uuid", y con esto se generan mismos nombres de archivo para varios comprobantes.
Quisiera poder usar el uuid para diferenciar los archivos y evitar que se colisionen/sobreescriban por tener el mismo nombre de archivo.

No logró encontrar donde obtienes y cargas los datos para generar el nombre.
¿Puedes darme el "norte" para localizar en que archivo y que funciones leen y llenan esos datos para el nombre de archivo? (mmh sospecho que necesito un IDE con depurador para "debugear", ¿alguno que me recomiendes?)

Mi nivel en Python en menos que intermedio. ;) Pero tu proyecto es genial para aprender cosas nuevas.

Y aprovechando:
¿Para la interfaz grafica (GUI) Usas algún editor de formas o es a "patín" la creación de la GUI que usas en este proyecto?

Saludos

**Comment by ghost** [comment]
Para la interfaz gráfica uso pygubu: https://github.com/alejandroautalan/pygubu
aunque a veces si soy medio masoquista y lo hago a "patín"...

Mira esta rama: https://github.com/LinuxCabal/admin-cfdi/tree/uuid_in_name

He agregado los cambios que mencionas para Py32 y el soporte para el UUID en la plantilla de nombre

Respecto a los IDEs, mi cariño se divide entre la sencillez de Geany y las excelente características de Ninja-IDE... pero, en esto hay para escoger...

Saludos
