### ISSUE TITLE
 Tengo problemas para descargar las facturas del SAT

### ISSUE THREAD

**Issue by pixelead0** [LinuxCabal/admin-cfdi#97]
Hola,

Tengo problemas para descargar las facturas del SAT.

Hasta antes de las actualizaciones de firefox funcionaba bien la opcion de descargar facturas recibidas y emitidas.

Con la ultima actualización de firefox v46.0.1 cuando le doy en descargar abre el navegador con una pagina en blanco, es decir no abre ninguna url y en el programa se queda la leyenda 'Abriendo Firefox'

He intentado debugear, pero no se en donde empezar.

Linux Mint 17.2
Firefox 46.0.1
Selenium 2.48.0
## 

Saludos

**Comment by ghost** [comment]
Mira si no es el mismo problema que tuve: https://github.com/LinuxCabal/admin-cfdi/issues/96

Saludos

**Comment by pixelead0** [comment]
He actualizado a selenium v2.53.5, sigo con el mismo problema.

**Comment by ghost** [comment]
En Linux Mint, ya esta Firefox 47, prueba a actualizarlo...

**Comment by pixelead0** [comment]
Lo he resuelto temporalmente haciendo un downgrade a Firefox 46.

Existe un issue en el repositorio de Selenium, en donde dice que regreses a Firefox 46 o implementemos Marionette.

https://github.com/SeleniumHQ/selenium/issues/2110

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by ghost** [comment]
Más fácil... no usar selenium: https://github.com/UniversoLibreMexicoAC/descargar-cfdi

**Comment by pixelead0** [comment]
Muchas gracias, funciona de maravilla y mucho más rapido.

**Comment by hriosm** [comment]
Perdon que ande de metiche pero tengo el mismo problema.
Sobre la liga  https://github.com/UniversoLibreMexicoAC/descargar-cfdi  , la intenté y no existe, me la podrías mandar corregida?

Gracias

**Comment by ghost** [comment]
Ese repositorio esta descontinuado. Este es el actual:
https://gitlab.com/mauriciobaeza/cfdi-descarga
