### ISSUE TITLE
abriendo firefox....

### ISSUE THREAD

**Issue by neomax2094** [LinuxCabal/admin-cfdi#99]
he estado tratando de bajar los xml pero ocurre el siguiente error:
click descarga -> "msj" abriendo firefox. pero no se abre.

pd: uso linux mint basado en ubuntu 16.04

saludos!

**Comment by ghost** [comment]
esta versión esta totalmente desactualizada, por favor, no la uses más...

versión funcional por aca: https://gitlab.com/mauriciobaeza/cfdi-descarga

Saludos

**Comment by neomax2094** [comment]
gracias por parte de fipasoft.com.mx
saludos!

**Comment by ghost** [comment]
Un abrazo para mis amigos de FipaSoft

**Comment by neomax2094** [comment]
que campos requiere la db sqlite? o ¿la db la crea el cfdi-descarga.py?

**Comment by ghost** [comment]
Por favor, usa el repositorio para las preguntas de ese proyecto... este no es el lugar... por otra parte, esta documentado en el wiki
